import { Component, computed, input, signal } from '@angular/core';
import { Product } from '../../models/product';

@Component({
  selector: 'app-products-grid',
  imports: [],
  template: `
    <div class="bg-gray-100 p-6">
      <h1 class="text-2xl font-bold text-gray-900">{{category()}}</h1>
      <div class="responsive-grid">
        @for (product of filteredProducts(); track product.id){
          <div class="bg-white cursor-pointer rounded-xl shadow-lg overflow-hidden flex flex-col h-full">
            <img [src]="product.imageUrl" class="w-full h-[300px] object-cover rounded-t-xl"/>
            <div class="p-5 flex flex-col flex-1">
              <h3 class="text-lg font-semibold text-gray-900 mb-2 leading-tight">{{product.name}}</h3>
            </div>
          </div>
        }
      </div>
    </div>

  `,
  styles: ``,
})
export default class ProductsGrid {
  
  category = input<string>('all');
  products = signal<Product[]>([
    {
      id: 1,
      name: "Mechanical Keyboard RGB",
      description: "Durable mechanical keyboard with RGB lighting and blue switches.",
      price: 89.99,
      imageUrl: "https://www.gskill.com/_upload/images/2303141832150.png",
      rating: 4.7,
      reviewCount: 134,
      inStock: true,
      category: "Electronics",
    },
    {
      id: 2,
      name: "Wireless Gaming Mouse",
      description: "Ergonomic mouse with high-precision sensor and customizable DPI.",
      price: 49.5,
      imageUrl: "https://i.ytimg.com/vi/gm4vPHHwIjo/maxresdefault.jpg",
      rating: 4.6,
      reviewCount: 220,
      inStock: true,
      category: "Electronics",
    },
    {
      id: 3,
      name: "27'' 4K Monitor",
      description: "Ultra HD IPS monitor with 144Hz refresh rate for smooth visuals.",
      price: 329.99,
      imageUrl: "https://source.unsplash.com/featured/?monitor",
      rating: 4.8,
      reviewCount: 95,
      inStock: true,
      category: "Electronics",
    },
    {
      id: 4,
      name: "Ultrabook 14'' Laptop",
      description: "Slim and powerful laptop with Intel i7, 16GB RAM, and 512GB SSD.",
      price: 999.0,
      imageUrl: "https://source.unsplash.com/featured/?laptop",
      rating: 4.5,
      reviewCount: 88,
      inStock: true,
      category: "Computers",
    },
    {
      id: 5,
      name: "Ergonomic Office Chair",
      description: "Comfortable adjustable chair with lumbar and head support.",
      price: 179.99,
      imageUrl: "https://source.unsplash.com/featured/?office-chair",
      rating: 4.4,
      reviewCount: 160,
      inStock: true,
      category: "Furniture",
    },
    {
      id: 6,
      name: "Noise Cancelling Headphones",
      description: "Wireless headphones with ANC and 30-hour battery life.",
      price: 149.99,
      imageUrl: "https://source.unsplash.com/featured/?headphones",
      rating: 4.6,
      reviewCount: 340,
      inStock: true,
      category: "Audio",
    },
    {
      id: 7,
      name: "Smartwatch Pro",
      description: "Fitness tracker with heart rate monitor and GPS support.",
      price: 159.99,
      imageUrl: "https://source.unsplash.com/featured/?smartwatch",
      rating: 4.3,
      reviewCount: 410,
      inStock: false,
      category: "Wearables",
    },
    {
      id: 8,
      name: "Android Tablet 10''",
      description: "HD display tablet with 64GB storage and long battery life.",
      price: 189.99,
      imageUrl: "https://source.unsplash.com/featured/?tablet",
      rating: 4.2,
      reviewCount: 90,
      inStock: true,
      category: "Electronics",
    },
    {
      id: 9,
      name: "DSLR Camera 24MP",
      description: "Professional camera with Wi-Fi and interchangeable lens.",
      price: 849.99,
      imageUrl: "https://source.unsplash.com/featured/?camera",
      rating: 4.9,
      reviewCount: 55,
      inStock: true,
      category: "Photography",
    },
    {
      id: 10,
      name: "Studio Microphone",
      description: "Professional condenser microphone for recording and streaming.",
      price: 109.99,
      imageUrl: "https://source.unsplash.com/featured/?microphone",
      rating: 4.5,
      reviewCount: 145,
      inStock: true,
      category: "Audio",
    },
    {
      id: 11,
      name: "Bluetooth Speaker",
      description: "Portable waterproof speaker with 12-hour battery life.",
      price: 59.99,
      imageUrl: "https://source.unsplash.com/featured/?speaker",
      rating: 4.4,
      reviewCount: 230,
      inStock: true,
      category: "Audio",
    },
    {
      id: 12,
      name: "1TB NVMe SSD",
      description: "High-speed solid state drive with ultra-fast read/write speeds.",
      price: 139.99,
      imageUrl: "https://source.unsplash.com/featured/?ssd",
      rating: 4.8,
      reviewCount: 300,
      inStock: true,
      category: "Storage",
    },
    {
      id: 13,
      name: "16GB DDR4 RAM",
      description: "High-performance 3200MHz DDR4 memory module.",
      price: 69.99,
      imageUrl: "https://source.unsplash.com/featured/?ram",
      rating: 4.7,
      reviewCount: 120,
      inStock: true,
      category: "Components",
    },
    {
      id: 14,
      name: "Wireless Charger",
      description: "Fast charging pad compatible with iPhone and Android.",
      price: 24.99,
      imageUrl: "https://source.unsplash.com/featured/?charger",
      rating: 4.2,
      reviewCount: 180,
      inStock: true,
      category: "Accessories",
    },
    {
      id: 15,
      name: "WiFi 6 Router",
      description: "High-speed dual-band router with advanced security features.",
      price: 129.99,
      imageUrl: "https://source.unsplash.com/featured/?router",
      rating: 4.6,
      reviewCount: 88,
      inStock: true,
      category: "Networking",
    },
    {
      id: 16,
      name: "Smart TV 55'' 4K",
      description: "4K Ultra HD smart TV with Android OS and voice assistant.",
      price: 699.99,
      imageUrl: "https://source.unsplash.com/featured/?smart-tv",
      rating: 4.5,
      reviewCount: 65,
      inStock: true,
      category: "Electronics",
    },
    {
      id: 17,
      name: "Multifunction Printer",
      description: "All-in-one printer with WiFi and scanning capabilities.",
      price: 119.99,
      imageUrl: "https://source.unsplash.com/featured/?printer",
      rating: 4.1,
      reviewCount: 105,
      inStock: true,
      category: "Office",
    },
    {
      id: 18,
      name: "Full HD Webcam",
      description: "1080p webcam with built-in microphone for meetings.",
      price: 59.99,
      imageUrl: "https://source.unsplash.com/featured/?webcam",
      rating: 4.4,
      reviewCount: 97,
      inStock: true,
      category: "Accessories",
    },
    {
      id: 19,
      name: "LED Projector",
      description: "Compact projector with HDMI and wireless screen mirroring.",
      price: 199.99,
      imageUrl: "https://source.unsplash.com/featured/?projector",
      rating: 4.3,
      reviewCount: 112,
      inStock: true,
      category: "Home Theater",
    },
    {
      id: 20,
      name: "Gaming Chair",
      description: "Comfortable adjustable chair with headrest and lumbar pillow.",
      price: 249.99,
      imageUrl: "https://source.unsplash.com/featured/?gaming-chair",
      rating: 4.5,
      reviewCount: 180,
      inStock: true,
      category: "Furniture",
    },
    {
      id: 21,
      name: "Smartphone 128GB",
      description: "5G smartphone with AMOLED display and dual cameras.",
      price: 699.99,
      imageUrl: "https://source.unsplash.com/featured/?smartphone",
      rating: 4.7,
      reviewCount: 210,
      inStock: true,
      category: "Mobile",
    },
    {
      id: 22,
      name: "External Hard Drive 2TB",
      description: "Portable USB 3.0 hard drive with fast data transfer.",
      price: 99.99,
      imageUrl: "https://source.unsplash.com/featured/?hard-drive",
      rating: 4.6,
      reviewCount: 300,
      inStock: true,
      category: "Storage",
    },
    {
      id: 23,
      name: "Mechanical Gaming Pad",
      description: "Customizable gaming keypad with programmable keys.",
      price: 59.99,
      imageUrl: "https://source.unsplash.com/featured/?gaming-pad",
      rating: 4.3,
      reviewCount: 80,
      inStock: true,
      category: "Gaming",
    },
    {
      id: 24,
      name: "Wireless Earbuds",
      description: "Compact true wireless earbuds with touch controls.",
      price: 79.99,
      imageUrl: "https://source.unsplash.com/featured/?earbuds",
      rating: 4.4,
      reviewCount: 250,
      inStock: true,
      category: "Audio",
    },
    {
      id: 25,
      name: "Mechanical Watch",
      description: "Luxury analog watch with stainless steel case.",
      price: 349.99,
      imageUrl: "https://source.unsplash.com/featured/?watch",
      rating: 4.8,
      reviewCount: 55,
      inStock: true,
      category: "Accessories",
    },
    {
      id: 26,
      name: "Action Camera 4K",
      description: "Waterproof action cam with stabilization and WiFi.",
      price: 229.99,
      imageUrl: "https://source.unsplash.com/featured/?action-camera",
      rating: 4.5,
      reviewCount: 130,
      inStock: true,
      category: "Photography",
    },
    {
      id: 27,
      name: "Drone with 1080p Camera",
      description: "Compact drone with live view and auto-stabilization.",
      price: 399.99,
      imageUrl: "https://source.unsplash.com/featured/?drone",
      rating: 4.6,
      reviewCount: 145,
      inStock: true,
      category: "Drones",
    },
    {
      id: 28,
      name: "USB-C Hub 7-in-1",
      description: "Expand your laptop with HDMI, USB, SD and Ethernet ports.",
      price: 59.99,
      imageUrl: "https://source.unsplash.com/featured/?usb-hub",
      rating: 4.4,
      reviewCount: 90,
      inStock: true,
      category: "Accessories",
    },
    {
      id: 29,
      name: "Gaming Console Controller",
      description: "Wireless controller with dual vibration and Bluetooth.",
      price: 69.99,
      imageUrl: "https://source.unsplash.com/featured/?controller",
      rating: 4.5,
      reviewCount: 200,
      inStock: true,
      category: "Gaming",
    },
    {
      id: 30,
      name: "VR Headset",
      description: "Virtual reality headset compatible with PC and mobile.",
      price: 499.99,
      imageUrl: "https://source.unsplash.com/featured/?vr-headset",
      rating: 4.7,
      reviewCount: 75,
      inStock: true,
      category: "Gaming",
    },
  ]
  );

  filteredProducts = computed(() => this.products().filter(product => product.category.toLowerCase() === this.category().toLowerCase()));
  test = computed(() => {
    console.log(this.category());
    return this.category();
  });
}
